#!/bin/bash

XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share
YADM_DIR=$XDG_DATA_HOME/yadm
system_type=$(uname -s)

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
if [ $(yadm -Y $YADM_DIR submodule status | grep '^-' | wc -l) -gt 0 ]; then
  echo "Init submodules"
  yadm -Y $YADM_DIR submodule update --recursive --init
else
  echo "Submodules already initialized"
fi

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$XDG_CONFIG_HOME/brew/Brewfile" ]; then
    echo "Updating homebrew bundle"
    # brew update && brew bundle --file=$XDG_CONFIG_HOME/brew/Brewfile
    brew update
  fi

fi
